FROM nvidia_ros_11.4:latest
 
# Change the default shell to Bash
SHELL [ "/bin/bash" , "-c" ]


# Install openai_ros
RUN cd ~/catkin_ws/src \
 && git clone -b kinetic-devel https://github.com/ncbdrck/openai_ros.git \
 && git clone https://ncbdrck@bitbucket.org/theconstructcore/theconstruct_msgs.git \
 && cd ~/catkin_ws \
 && rosdep install --from-paths src --ignore-src -r -y

RUN cd ~/catkin_ws \
 && source devel/setup.bash \
 && catkin_make \
 && source devel/setup.bash
 
 
 # Install Fetch robot
RUN source /opt/ros/noetic/setup.bash \
 && cd ~/catkin_ws/src \
 && git clone -b noetic https://ncbdrck@bitbucket.org/theconstructcore/fetch_tc.git \
 && git clone https://ncbdrck@bitbucket.org/theconstructcore/spawn_robot_tools.git \
 && git clone https://github.com/mikeferguson/simple_grasping.git \
 && cd ~/catkin_ws \
 && rosdep install --from-paths src --ignore-src -r -y

RUN cd ~/catkin_ws \
 && source devel/setup.bash \
 && catkin_make \
 && source devel/setup.bash
 
# Install iri_wam robot
RUN source /opt/ros/noetic/setup.bash \
 && cd ~/catkin_ws/src \
 && git clone -b noetic https://ncbdrck@bitbucket.org/theconstructcore/iri_wam.git \
 && git clone https://ncbdrck@bitbucket.org/theconstructcore/hokuyo_model.git \
 && cd ~/catkin_ws \
 && rosdep install --from-paths src --ignore-src -r -y

RUN cd ~/catkin_ws \
 && source devel/setup.bash \
 && catkin_make \
 && source devel/setup.bash
