FROM nvidia_ros:latest
 
# Change the default shell to Bash
SHELL [ "/bin/bash" , "-c" ]

# Install ROS packages
RUN apt-get update
RUN apt-get install -y ros-noetic-ros-control ros-noetic-ros-controllers ros-noetic-moveit ros-noetic-navigation ros-noetic-perception
RUN apt-get update
RUN apt-get install -y ros-noetic-gazebo-ros-pkgs ros-noetic-gazebo-ros-control ros-noetic-fkie-multimaster 
RUN apt-get update
RUN apt-get install -y python3-rosdep python3-rosinstall python3-rosinstall-generator python3-wstool build-essential

# Install pip
RUN apt-get update
RUN apt-get install -y python3-pip
RUN ln -s /usr/bin/python3 /usr/bin/python

# Install pytorch
RUN pip3 install torch==1.9.0+cu111 torchvision==0.10.0+cu111 torchaudio==0.9.0 -f https://download.pytorch.org/whl/torch_stable.html

# Install tensorflow
RUN pip3 install --upgrade tensorflow-gpu

# Install other python packages
RUN pip install gym

# Install Git
RUN apt-get update && apt-get install -y git
 
# Create a Catkin workspace
RUN source /opt/ros/noetic/setup.bash \
 && mkdir -p ~/catkin_ws/src \
 && cd ~/catkin_ws/ \
 && catkin_make \
 && source devel/setup.bash

RUN echo "source ~/catkin_ws/devel/setup.bash" >> ~/.bashrc
RUN source ~/.bashrc

# Install openai_ros
RUN cd ~/catkin_ws/src \
 && git clone -b kinetic-devel https://github.com/ncbdrck/openai_ros.git \
 && git clone https://ncbdrck@bitbucket.org/theconstructcore/theconstruct_msgs.git \
 && cd ~/catkin_ws \
 && rosdep install --from-paths src --ignore-src -r -y

RUN cd ~/catkin_ws \
 && source devel/setup.bash \
 && catkin_make \
 && source devel/setup.bash
