FROM nvidia_ros_11.4:latest
 
# Change the default shell to Bash
SHELL [ "/bin/bash" , "-c" ]

# Install miniconda
ENV CONDA_DIR /opt/conda
RUN wget --quiet https://repo.anaconda.com/miniconda/Miniconda3-latest-Linux-x86_64.sh -O ~/miniconda.sh && \
     /bin/bash ~/miniconda.sh -b -p /opt/conda

# Put conda in path so we can use conda activate
ENV PATH=$CONDA_DIR/bin:$PATH

# Install tensorflow
RUN conda install -c conda-forge cudatoolkit=11.2 cudnn=8.1.0
RUN echo "export LD_LIBRARY_PATH=$LD_LIBRARY_PATH:$CONDA_PREFIX/lib/" >> ~/.bashrc

# RUN apt-get install -y --no-install-recommends cuda-toolkit-11-2
# RUN apt-get update
# RUN apt-get install -y --no-install-recommends cuda-11-2 libcudnn8=8.1.0.77-1+cuda11.2 libcudnn8-dev=8.1.0.77-1+cuda11.2

RUN source ~/.bashrc
RUN pip install --upgrade pip
RUN pip install tensorflow
# RUN pip3 install --upgrade tensorflow-gpu
RUN pip install stable-baselines3[extra]

# Simulations
RUN source /opt/ros/noetic/setup.bash \
 && mkdir -p ~/simulation_ws/src \
 && cd ~/simulation_ws/ \
 && catkin_make \
 && source devel/setup.bash

RUN echo "source ~/simulation_ws/devel/setup.bash" >> ~/.bashrc
RUN source ~/.bashrc

# Create a Catkin workspace
RUN source /opt/ros/noetic/setup.bash \
 && mkdir -p ~/catkin_ws/src \
 && cd ~/catkin_ws/ \
 && catkin_make \
 && source devel/setup.bash

RUN echo "source ~/catkin_ws/devel/setup.bash" >> ~/.bashrc
RUN source ~/.bashrc

# Install openai_ros
RUN cd ~/catkin_ws/src \
 && git clone -b kinetic-devel https://github.com/ncbdrck/openai_ros.git \
 && git clone https://ncbdrck@bitbucket.org/theconstructcore/theconstruct_msgs.git \
 && cd ~/catkin_ws \
 && rosdep install --from-paths src --ignore-src -r -y

RUN cd ~/catkin_ws \
 && source devel/setup.bash \
 && catkin_make \
 && source devel/setup.bash
 
# Install Fetch robot
RUN source /opt/ros/noetic/setup.bash \
 && cd ~/catkin_ws/src \
 && git clone -b noetic https://ncbdrck@bitbucket.org/theconstructcore/fetch_tc.git \
 && git clone https://ncbdrck@bitbucket.org/theconstructcore/spawn_robot_tools.git \
 && git clone https://github.com/mikeferguson/simple_grasping.git \
 && cd ~/catkin_ws \
 && rosdep install --from-paths src --ignore-src -r -y

RUN cd ~/catkin_ws \
 && source devel/setup.bash \
 && catkin_make \
 && source devel/setup.bash
 
# Install iri_wam robot
RUN source /opt/ros/noetic/setup.bash \
 && cd ~/catkin_ws/src \
 && git clone -b noetic https://ncbdrck@bitbucket.org/theconstructcore/iri_wam.git \
 && git clone https://ncbdrck@bitbucket.org/theconstructcore/hokuyo_model.git \
 && cd ~/catkin_ws \
 && rosdep install --from-paths src --ignore-src -r -y

RUN cd ~/catkin_ws \
 && source devel/setup.bash \
 && catkin_make \
 && source devel/setup.bash
