FROM nvidia/cudagl:11.4.0-base-ubuntu20.04

# Minimal setup
RUN apt-get update \
 && apt-get install -y locales lsb-release
ARG DEBIAN_FRONTEND=noninteractive
RUN dpkg-reconfigure locales

# upgrade the packages
RUN apt-get update
RUN apt-get upgrade -y
 
# Install ROS Noetic
RUN sh -c 'echo "deb http://packages.ros.org/ros/ubuntu $(lsb_release -sc) main" > /etc/apt/sources.list.d/ros-latest.list'
RUN apt-key adv --keyserver 'hkp://keyserver.ubuntu.com:80' --recv-key C1CF6E31E6BADE8868B172B4F42ED6FBAB17C654
RUN apt-get update \
 && apt-get install -y --no-install-recommends ros-noetic-desktop-full
RUN apt-get install -y --no-install-recommends python3-rosdep python3-rosinstall python3-rosinstall-generator python3-wstool build-essential
RUN apt-get install -y curl wget
RUN rosdep init \
 && rosdep fix-permissions \
 && rosdep update
RUN echo "source /opt/ros/noetic/setup.bash" >> ~/.bashrc

# Install pip
RUN apt-get update
RUN apt-get install -y python3-pip
RUN ln -s /usr/bin/python3 /usr/bin/python

# Install ROS packages
RUN apt-get update
RUN apt-get install -y    
RUN apt-get update
RUN apt-get install -y 
RUN apt-get update
RUN apt-get install -y 

sudo apt install -y git-all python3-colcon-common-extensions python3-vcstool python3-catkin-tools
sudo apt install -y libcanberra-gtk-module libcanberra-gtk3-module 
sudo apt install -y ros-noetic-moveit ros-noetic-moveit-resources-prbt-moveit-config
sudo apt install -y ros-noetic-pilz-industrial-motion-planner ros-noetic-industrial-core
sudo apt install -y ros-noetic-rviz-visual-tools ros-noetic-moveit-visual-tools ros-noetic-tf-conversions 
sudo apt install -y ros-noetic-gazebo-ros-pkgs ros-noetic-gazebo-ros-control ros-noetic-joint-state-controller ros-noetic-fkie-multimaster
sudo apt install -y ros-noetic-ros-control ros-noetic-ros-controllers ros-noetic-navigation ros-noetic-perception
sudo apt install -y ros-noetic-gazebo-ros ros-noetic-control-toolbox ros-noetic-realtime-tools ros-noetic-xacro ros-noetic-kdl-parser
sudo apt install -y git-core python3-vcstools ros-noetic-control-msgs ros-noetic-xacro ros-noetic-tf2-ros ros-noetic-rviz ros-noetic-cv-bridge ros-noetic-actionlib ros-noetic-actionlib-msgs ros-noetic-dynamic-reconfigure ros-noetic-trajectory-msgs ros-noetic-rospy-message-converter


# upgrade the packages
RUN apt-get update
RUN apt-get upgrade -y
