FROM nvidia_ros:latest
 
# Change the default shell to Bash
SHELL [ "/bin/bash" , "-c" ]

# Install ROS packages
RUN apt-get update
RUN apt-get install -y ros-noetic-ros-control ros-noetic-ros-controllers ros-noetic-moveit ros-noetic-navigation ros-noetic-perception
RUN apt-get update
RUN apt-get install -y ros-noetic-gazebo-ros-pkgs ros-noetic-gazebo-ros-control ros-noetic-fkie-multimaster 
RUN apt-get update
RUN apt-get install -y python3-rosdep python3-rosinstall python3-rosinstall-generator python3-wstool build-essential

# Install pip
RUN apt-get update
RUN apt-get install -y python3-pip

# Install pytorch
RUN pip3 install torch==1.9.0+cu111 torchvision==0.10.0+cu111 torchaudio==0.9.0 -f https://download.pytorch.org/whl/torch_stable.html

# Install tensorflow
RUN pip install --upgrade tensorflow

# Install other python packages
RUN pip install gym

# Install Git
RUN apt-get update && apt-get install -y git
 
# Create a Catkin workspace
RUN source /opt/ros/noetic/setup.bash \
 && mkdir -p ~/catkin_ws/src \
 && cd ~/catkin_ws/ \
 && catkin_make \
 && source devel/setup.bash

RUN echo "source ~/catkin_ws/devel/setup.bash" >> ~/.bashrc
RUN source ~/.bashrc

# Install openai_ros
RUN cd ~/catkin_ws/src \
 && git clone -b version2 https://github.com/ncbdrck/openai_ros_noetic.git \
 && git clone https://ncbdrck@bitbucket.org/theconstructcore/theconstruct_msgs.git \
 && cd ~/catkin_ws \
 && rosdep install --from-paths src --ignore-src -r -y \
 && catkin_make \
 && source devel/setup.bash
 
# Install Robots for the project
# Fetch robot
RUN cd ~/catkin_ws/src \
 && git clone -b noetic https://ncbdrck@bitbucket.org/theconstructcore/fetch_tc.git \
 && git clone https://ncbdrck@bitbucket.org/theconstructcore/spawn_robot_tools.git \
 && git clone https://github.com/mikeferguson/simple_grasping.git \
 && cd ~/catkin_ws \
 && rosdep install --from-paths src --ignore-src -r -y \
 && catkin_make \
 && source devel/setup.bash

# iri_wam robot
RUN cd ~/catkin_ws/src \
 && git clone -b noetic https://ncbdrck@bitbucket.org/theconstructcore/iri_wam.git \
 && git clone https://ncbdrck@bitbucket.org/theconstructcore/hokuyo_model.git \
 && cd ~/catkin_ws \
 && rosdep install --from-paths src --ignore-src -r -y \
 && catkin_make \
 && source devel/setup.bash
