FROM nvidia_ros_11.2.2:latest
 
# Change the default shell to Bash
SHELL [ "/bin/bash" , "-c" ]

# Install miniconda
ENV CONDA_DIR /opt/conda
RUN wget --quiet https://repo.anaconda.com/miniconda/Miniconda3-latest-Linux-x86_64.sh -O ~/miniconda.sh && \
     /bin/bash ~/miniconda.sh -b -p /opt/conda

# Put conda in path so we can use conda activate
ENV PATH=$CONDA_DIR/bin:$PATH

# Install tensorflow
# RUN conda install -c conda-forge cudatoolkit=11.2 cudnn=8.1.0
# RUN conda install -c conda-forge cudatoolkit=11.2 cudnn=8.2.4
# RUN echo "export LD_LIBRARY_PATH=$LD_LIBRARY_PATH:$CONDA_PREFIX/lib/" >> ~/.bashrc

# RUN apt-get install -y --no-install-recommends cuda-toolkit-11-2
# RUN apt-get update
# RUN apt-get install -y --no-install-recommends cuda-11-2 libcudnn8=8.1.0.77-1+cuda11.2 libcudnn8-dev=8.1.0.77-1+cuda11.2

RUN source ~/.bashrc
RUN pip install --upgrade pip
# RUN pip install tensorflow
RUN pip3 install --upgrade tensorflow-gpu
RUN pip install stable-baselines3[extra]
